service: line-nba-state
provider:
  name: aws
  runtime: python3.7

functions:
  line_bot:
    handler: handler.webhook
    events:
      - http:
          path: /webhook
          method: POST
custom:
  pythonRequirements:
    dockerizePip: true

plugins:
  - serverless-python-requirements
